### ISSUE TITLE
Upload instructions

### ISSUE THREAD

**Issue by giraffe167** [DCC-EX/EX-T3-WiFi#50]
Iam only really a begginer with using esp32's it would be nice if you could make a step by step instructions to even a video showing how to uploading the code to the esp!

**Comment by alex-code** [comment]
I'm not the best at explaining/instructions.
There's a quick start guide here, https://docs.platformio.org/en/latest/integration/ide/vscode.html#quick-start

I'm looking into browser based uploading so you'd only need a Chromium based browser.
Will avoid the need to install IDE's and build the code yourself.

**Comment by daveclifford** [comment]
**"I'm looking into browser based uploading so you'd only need a Chromium based browser.
Will avoid the need to install IDE's and build the code yourself"**

I believe that you will become more famous than you are now.....

I have been developing software  since 1970 and I don't think anyone who hasn't used an IDE would be able to go through the steps to **successfully**: 
 
a) install two software tools, and 
b) use PlatformIO to build/upload the build to a FireBeetle2.

More know how to use the Arduino IDE than  the VSCode/PlatformIO combo.

Very few will help you add function to your code..., but most will love to upload the current build to their WiFi Throttle that they built themselves  (pride of build and ownership).

I whole-hardily applaud your interest in providing a binary build file that will be uploaded by a Chromium browser.

Dave

**Comment by giraffe167** [comment]
Thank you that worked
